import Vue from 'vue'
import App from './App.vue'
import router from './router'


import myLibrary from 'my-library'
Vue.use(myLibrary)

// import { Button } from 'my-library'
// Vue.component(Button.name, Button)
// import 'my-library/theme/button.css'
// import 'my-library/theme/index.css'
// import '@/assets/ui-variables.scss'
import 'my-library/theme/alert.css'
import 'my-library/theme/aside.css'
import 'my-library/theme/autocomplete.css'
import 'my-library/theme/avatar.css'
import 'my-library/theme/backtop.css'
import 'my-library/theme/badge.css'
import 'my-library/theme/base.css'
import 'my-library/theme/breadcrumb-item.css'
import 'my-library/theme/breadcrumb.css'
import 'my-library/theme/button-group.css'
import 'my-library/theme/button.css'
import 'my-library/theme/calendar.css'
import 'my-library/theme/card.css'
import 'my-library/theme/carousel-item.css'
import 'my-library/theme/carousel.css'
import 'my-library/theme/cascader-panel.css'
import 'my-library/theme/cascader.css'
import 'my-library/theme/checkbox-button.css'
import 'my-library/theme/checkbox-group.css'
import 'my-library/theme/checkbox.css'
import 'my-library/theme/col.css'
import 'my-library/theme/collapse-item.css'
import 'my-library/theme/collapse.css'
import 'my-library/theme/color-picker.css'
import 'my-library/theme/container.css'
import 'my-library/theme/date-picker.css'
import 'my-library/theme/dialog.css'
import 'my-library/theme/display.css'
import 'my-library/theme/divider.css'
import 'my-library/theme/drawer.css'
import 'my-library/theme/dropdown-item.css'
import 'my-library/theme/dropdown-menu.css'
import 'my-library/theme/dropdown.css'
import 'my-library/theme/footer.css'
import 'my-library/theme/form-item.css'
import 'my-library/theme/form.css'
import 'my-library/theme/header.css'
import 'my-library/theme/icon.css'
import 'my-library/theme/image.css'
import 'my-library/theme/index.css'
import 'my-library/theme/infinite-scroll.css'
import 'my-library/theme/infiniteScroll.css'
import 'my-library/theme/input-number.css'
import 'my-library/theme/input.css'
import 'my-library/theme/link.css'
import 'my-library/theme/loading.css'
import 'my-library/theme/main.css'
import 'my-library/theme/menu-item-group.css'
import 'my-library/theme/menu-item.css'
import 'my-library/theme/menu.css'
import 'my-library/theme/message-box.css'
import 'my-library/theme/message.css'
import 'my-library/theme/notification.css'
import 'my-library/theme/option-group.css'
import 'my-library/theme/option.css'
import 'my-library/theme/page-header.css'
import 'my-library/theme/pagination.css'
import 'my-library/theme/popconfirm.css'
import 'my-library/theme/popover.css'
import 'my-library/theme/popper.css'
import 'my-library/theme/progress.css'
import 'my-library/theme/radio-button.css'
import 'my-library/theme/radio-group.css'
import 'my-library/theme/radio.css'
import 'my-library/theme/rate.css'
import 'my-library/theme/reset.css'
import 'my-library/theme/row.css'
import 'my-library/theme/scrollbar.css'
import 'my-library/theme/select-dropdown.css'
import 'my-library/theme/select.css'
import 'my-library/theme/slider.css'
import 'my-library/theme/spinner.css'
import 'my-library/theme/step.css'
import 'my-library/theme/steps.css'
import 'my-library/theme/submenu.css'
import 'my-library/theme/switch.css'
import 'my-library/theme/tab-pane.css'
import 'my-library/theme/table-column.css'
import 'my-library/theme/table.css'
import 'my-library/theme/tabs.css'
import 'my-library/theme/tag.css'
import 'my-library/theme/time-picker.css'
import 'my-library/theme/time-select.css'
import 'my-library/theme/timeline-item.css'
import 'my-library/theme/timeline.css'
import 'my-library/theme/tooltip.css'
import 'my-library/theme/transfer.css'
import 'my-library/theme/tree.css'
import 'my-library/theme/upload.css'

Vue.config.productionTip = false

new Vue({
  router,
  render: function (h) { return h(App) }
}).$mount('#app')
